export async function generateMetadata() {
  const data = await fetch(`http://localhost:3000/api/user`, {
    // *GET, POST, PATCH, PUT, DELETE
    method: "POST",
    headers: {
      Accept: "application/json",
      "Content-Type": "application/json",
    },
    // For POST, PATCH, and PUT requests
    body: JSON.stringify({ key: "value" }),
  }).then((response) => response.json());

  return {
    title: data.message,
    description: "Generated by create next app",
  };
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
